//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaCamp.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apodo { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<decimal> Estatura { get; set; }
        public Nullable<int> Peso { get; set; }
        public string Posicion { get; set; }
        public Nullable<int> IdEquipo { get; set; }
    }
}
